#' Configure ggWebGL Transport Options
#'
#' `ggwebgl_transport()` controls how large renderer payloads are encoded before
#' they are handed to the browser. Small scenes keep the existing JSON arrays by
#' default; large point layers can use base64 typed arrays, palette color lookup,
#' deterministic preview LOD, and progressive GPU upload.
#'
#' @param mode Transport mode. `"auto"` compacts point layers at or above
#'   `threshold`, `"compact"` compacts all point layers, and `"legacy"` keeps the
#'   original JSON-array payloads.
#' @param threshold Row threshold used when `mode = "auto"`.
#' @param progressive Progressive upload policy. `"auto"` enables progressive
#'   upload for compact layers, `"on"` forces it, and `"off"` disables it.
#' @param chunk_size Number of points per progressive upload chunk.
#' @param position Position encoding, either `"float32"` or `"quantized"`.
#' @param colors Color encoding. `"auto"` uses palette lookup when beneficial and
#'   byte RGBA otherwise; `"palette"` requires palette lookup when possible; and
#'   `"rgba"` stores byte RGBA.
#' @param lod LOD preview policy. `"auto"` generates deterministic grid previews
#'   for compact point layers, `"grid"` forces them, and `"none"` disables them.
#' @param lod_max_points Maximum number of preview points generated by the grid
#'   LOD helper.
#'
#' @return A normalized `ggwebgl_transport` list.
#'
#' @examples
#' ggwebgl_transport(threshold = 100000L, chunk_size = 50000L)
#' @export
ggwebgl_transport <- function(mode = c("auto", "compact", "legacy"),
                              threshold = 100000L,
                              progressive = c("auto", "on", "off"),
                              chunk_size = 100000L,
                              position = c("float32", "quantized"),
                              colors = c("auto", "palette", "rgba"),
                              lod = c("auto", "grid", "none"),
                              lod_max_points = 5000L) {
  out <- list(
    mode = as.character(mode)[[1L]],
    threshold = threshold,
    progressive = as.character(progressive)[[1L]],
    chunk_size = chunk_size,
    position = as.character(position)[[1L]],
    colors = as.character(colors)[[1L]],
    lod = as.character(lod)[[1L]],
    lod_max_points = lod_max_points
  )
  out <- normalise_transport(out)
  class(out) <- c("ggwebgl_transport", "list")
  out
}

normalise_transport <- function(transport = NULL) {
  defaults <- list(
    mode = "auto",
    threshold = 100000L,
    progressive = "auto",
    chunk_size = 100000L,
    position = "float32",
    colors = "auto",
    lod = "auto",
    lod_max_points = 5000L
  )

  if (inherits(transport, "ggwebgl_transport")) {
    transport <- unclass(transport)
  }
  if (is.null(transport)) {
    transport <- list()
  }
  if (!is.list(transport)) {
    rlang::abort("`transport` must be a list created by `ggwebgl_transport()`.")
  }

  mode <- tolower(as.character(transport$mode %||% defaults$mode)[[1L]])
  if (!mode %in% c("auto", "compact", "legacy")) {
    rlang::abort("`transport$mode` must be one of \"auto\", \"compact\", or \"legacy\".")
  }

  progressive <- tolower(as.character(transport$progressive %||% defaults$progressive)[[1L]])
  if (!progressive %in% c("auto", "on", "off")) {
    rlang::abort("`transport$progressive` must be one of \"auto\", \"on\", or \"off\".")
  }

  position <- tolower(as.character(transport$position %||% defaults$position)[[1L]])
  if (!position %in% c("float32", "quantized")) {
    rlang::abort("`transport$position` must be one of \"float32\" or \"quantized\".")
  }

  colors <- tolower(as.character(transport$colors %||% defaults$colors)[[1L]])
  if (!colors %in% c("auto", "palette", "rgba")) {
    rlang::abort("`transport$colors` must be one of \"auto\", \"palette\", or \"rgba\".")
  }

  lod <- tolower(as.character(transport$lod %||% defaults$lod)[[1L]])
  if (!lod %in% c("auto", "grid", "none")) {
    rlang::abort("`transport$lod` must be one of \"auto\", \"grid\", or \"none\".")
  }

  threshold <- as.integer(transport$threshold %||% defaults$threshold)[[1L]]
  if (!is.finite(threshold) || threshold < 1L) {
    rlang::abort("`transport$threshold` must be a positive integer scalar.")
  }

  chunk_size <- as.integer(transport$chunk_size %||% defaults$chunk_size)[[1L]]
  if (!is.finite(chunk_size) || chunk_size < 1L) {
    rlang::abort("`transport$chunk_size` must be a positive integer scalar.")
  }

  lod_max_points <- as.integer(transport$lod_max_points %||% defaults$lod_max_points)[[1L]]
  if (!is.finite(lod_max_points) || lod_max_points < 1L) {
    rlang::abort("`transport$lod_max_points` must be a positive integer scalar.")
  }

  compact_list(list(
    mode = mode,
    threshold = threshold,
    progressive = progressive,
    chunk_size = chunk_size,
    position = position,
    colors = colors,
    lod = lod,
    lod_max_points = lod_max_points
  ))
}

ggwebgl_transport_should_compact <- function(layer, transport) {
  if (!identical(layer$type, "points")) {
    return(FALSE)
  }
  rows <- as.integer(layer$rows %||% 0L)
  if (!is.finite(rows) || rows < 1L) {
    return(FALSE)
  }
  if (identical(transport$mode, "legacy")) {
    return(FALSE)
  }
  if (identical(transport$mode, "compact")) {
    return(TRUE)
  }
  rows >= transport$threshold
}

ggwebgl_apply_transport <- function(render, webgl) {
  transport <- normalise_transport(webgl$transport %||% NULL)
  compact_layers <- 0L
  compact_point_count <- 0L
  decoded_bytes <- 0

  panels <- lapply(render$panels %||% list(), function(panel) {
    panel$layers <- lapply(panel$layers %||% list(), function(layer) {
      if (!ggwebgl_transport_should_compact(layer, transport)) {
        return(layer)
      }
      compact_layer <- ggwebgl_compact_point_layer(layer, transport)
      compact_layers <<- compact_layers + 1L
      compact_point_count <<- compact_point_count + as.integer(compact_layer$rows %||% 0L)
      decoded_bytes <<- decoded_bytes + as.numeric(compact_layer$compact$decoded_bytes %||% 0)
      compact_layer
    })
    panel
  })

  render$panels <- panels
  render$transport <- compact_list(list(
    mode = transport$mode,
    threshold = transport$threshold,
    position = transport$position,
    colors = transport$colors,
    progressive = transport$progressive,
    chunk_size = transport$chunk_size,
    compact_layers = compact_layers,
    compact_point_count = compact_point_count,
    decoded_bytes = decoded_bytes
  ))
  render$lod <- compact_list(list(
    point_strategy = if (compact_layers > 0L && !identical(transport$lod, "none")) "grid" else NULL,
    mesh_hooks = "external"
  ))

  derive_single_panel_compatibility(render)
}

ggwebgl_compact_point_layer <- function(layer, transport) {
  n <- as.integer(layer$rows %||% 0L)
  position <- ggwebgl_compact_point_positions(layer, transport)
  color <- ggwebgl_compact_point_colors(layer$rgba, n, transport)
  attributes <- compact_list(list(
    size = ggwebgl_compact_numeric_attribute(layer$size %||% rep(1, n), n, default = 1),
    age = ggwebgl_compact_numeric_attribute(layer$age %||% rep(1, n), n, default = 1)
  ))
  progressive <- identical(transport$progressive, "on") ||
    (identical(transport$progressive, "auto") && n >= transport$threshold)
  lod <- if (!identical(transport$lod, "none")) {
    ggwebgl_point_lod_grid(layer, max_points = transport$lod_max_points)
  } else {
    NULL
  }

  layer$compact <- compact_list(list(
    version = 1L,
    primitive = "points",
    rows = n,
    position = position,
    color = color,
    attributes = attributes,
    decoded_bytes = ggwebgl_compact_decoded_bytes(position, color, attributes)
  ))
  layer$transport <- compact_list(list(
    mode = "compact",
    encoding = "base64_typed_array",
    progressive = progressive,
    chunk_size = transport$chunk_size
  ))
  layer$lod <- lod
  layer$x <- NULL
  layer$y <- NULL
  layer$z <- NULL
  layer$rgba <- NULL
  layer$size <- NULL
  layer$age <- NULL
  layer
}

ggwebgl_compact_point_positions <- function(layer, transport) {
  n <- as.integer(layer$rows %||% 0L)
  x <- as.numeric(layer$x %||% numeric())
  y <- as.numeric(layer$y %||% numeric())
  z <- if (length(layer$z %||% NULL)) as.numeric(layer$z) else NULL
  components <- if (length(z) >= n) 3L else 2L
  values <- if (components == 3L) {
    as.numeric(t(cbind(x[seq_len(n)], y[seq_len(n)], z[seq_len(n)])))
  } else {
    as.numeric(t(cbind(x[seq_len(n)], y[seq_len(n)])))
  }
  ranges <- compact_list(list(
    x = normalise_range(range(x, finite = TRUE)),
    y = normalise_range(range(y, finite = TRUE)),
    z = if (components == 3L) normalise_range(range(z, finite = TRUE)) else NULL
  ))

  if (identical(transport$position, "quantized")) {
    q <- ggwebgl_quantize_positions(x, y, z, n, ranges, components)
    return(compact_list(list(
      encoding = "uint16_base64",
      components = components,
      rows = n,
      data = ggwebgl_encode_uint16_base64(q),
      ranges = ranges
    )))
  }

  compact_list(list(
    encoding = "float32_base64",
    components = components,
    rows = n,
    data = ggwebgl_encode_float32_base64(values),
    ranges = ranges
  ))
}

ggwebgl_quantize_positions <- function(x, y, z, n, ranges, components) {
  quantize_one <- function(values, range) {
    span <- diff(range)
    if (!is.finite(span) || span <= 0) {
      return(rep(0L, n))
    }
    pmax(0L, pmin(65535L, as.integer(round((values[seq_len(n)] - range[[1L]]) / span * 65535))))
  }

  qx <- quantize_one(x, ranges$x)
  qy <- quantize_one(y, ranges$y)
  if (components == 3L) {
    qz <- quantize_one(z, ranges$z)
    as.integer(t(cbind(qx, qy, qz)))
  } else {
    as.integer(t(cbind(qx, qy)))
  }
}

ggwebgl_compact_numeric_attribute <- function(values, n, default = 0) {
  values <- as.numeric(values %||% rep(default, n))
  if (length(values) < n) {
    values <- rep(values, length.out = n)
  }
  values <- values[seq_len(n)]
  values[!is.finite(values)] <- default
  if (!length(values) || all(values == values[[1L]])) {
    return(list(encoding = "constant", value = as.numeric(values[[1L]] %||% default), length = n))
  }
  list(
    encoding = "float32_base64",
    length = n,
    data = ggwebgl_encode_float32_base64(values)
  )
}

ggwebgl_compact_point_colors <- function(rgba, n, transport) {
  rgba <- ggwebgl_rgba_u8_matrix(rgba, n)
  if (identical(transport$colors, "rgba")) {
    return(list(
      encoding = "rgba_u8_base64",
      rows = n,
      data = ggwebgl_encode_uint8_base64(as.integer(t(rgba)))
    ))
  }

  keys <- apply(rgba, 1L, paste, collapse = ",")
  palette_keys <- unique(keys)
  palette_size <- length(palette_keys)
  use_palette <- identical(transport$colors, "palette") ||
    (identical(transport$colors, "auto") && palette_size < n && palette_size <= 65536L)

  if (!use_palette) {
    return(list(
      encoding = "rgba_u8_base64",
      rows = n,
      data = ggwebgl_encode_uint8_base64(as.integer(t(rgba)))
    ))
  }

  palette_index <- match(keys, palette_keys) - 1L
  palette_rows <- rgba[match(palette_keys, keys), , drop = FALSE]
  index_encoding <- if (palette_size <= 65536L) "uint16_base64" else "uint32_base64"
  index_data <- if (identical(index_encoding, "uint16_base64")) {
    ggwebgl_encode_uint16_base64(palette_index)
  } else {
    ggwebgl_encode_uint32_base64(palette_index)
  }

  list(
    encoding = "palette_rgba_u8",
    rows = n,
    palette_size = palette_size,
    palette = ggwebgl_encode_uint8_base64(as.integer(t(palette_rows))),
    index_encoding = index_encoding,
    index = index_data
  )
}

ggwebgl_rgba_u8_matrix <- function(rgba, n) {
  rgba <- as.numeric(rgba %||% rep(c(0, 0, 0, 1), n))
  if (length(rgba) < n * 4L) {
    rgba <- rep(rgba, length.out = n * 4L)
  }
  rgba <- matrix(rgba[seq_len(n * 4L)], ncol = 4L, byrow = TRUE)
  if (any(rgba > 1.5, na.rm = TRUE)) {
    rgba <- rgba / 255
  }
  rgba[!is.finite(rgba)] <- 0
  rgba[, 4L] <- pmax(0, pmin(1, rgba[, 4L]))
  out <- pmax(0L, pmin(255L, as.integer(round(rgba * 255))))
  dim(out) <- dim(rgba)
  out
}

ggwebgl_compact_decoded_bytes <- function(position, color, attributes) {
  position_bytes <- as.integer(position$rows %||% 0L) *
    as.integer(position$components %||% 0L) *
    if (identical(position$encoding, "uint16_base64")) 2L else 4L
  color_bytes <- if (identical(color$encoding, "palette_rgba_u8")) {
    as.integer(color$palette_size %||% 0L) * 4L +
      as.integer(color$rows %||% 0L) * if (identical(color$index_encoding, "uint16_base64")) 2L else 4L
  } else {
    as.integer(color$rows %||% 0L) * 4L
  }
  attribute_bytes <- sum(vapply(attributes, function(attr) {
    if (identical(attr$encoding, "constant")) 8 else as.integer(attr$length %||% 0L) * 4L
  }, numeric(1)))
  position_bytes + color_bytes + attribute_bytes
}

ggwebgl_encode_float32_base64 <- function(x) {
  ggwebgl_base64_raw(writeBin(as.numeric(x), raw(), size = 4L, endian = "little"))
}

ggwebgl_encode_uint16_base64 <- function(x) {
  x <- pmax(0, pmin(65535, as.integer(x)))
  bytes <- as.integer(rbind(x %% 256L, x %/% 256L))
  ggwebgl_base64_raw(as.raw(bytes))
}

ggwebgl_encode_uint32_base64 <- function(x) {
  x <- pmax(0, as.numeric(x))
  b0 <- x %% 256
  b1 <- floor(x / 256) %% 256
  b2 <- floor(x / 65536) %% 256
  b3 <- floor(x / 16777216) %% 256
  ggwebgl_base64_raw(as.raw(as.integer(rbind(b0, b1, b2, b3))))
}

ggwebgl_encode_uint8_base64 <- function(x) {
  ggwebgl_base64_raw(as.raw(pmax(0L, pmin(255L, as.integer(x)))))
}

ggwebgl_base64_raw <- function(x) {
  gsub("[\r\n]", "", jsonlite::base64_enc(x))
}
